###########################
#        POSTS            #
###########################

enum VisibilitySetting {
  PUBLIC
  FOLLOWERS_ONLY
  PRIVATE
}

enum MediaType {
  IMAGE
  VIDEO
  AUDIO
}

"""An attachment in a post."""
type MediaAttachment {
  id:   String
  url:  String
  cid:  String
  title:  String
  type: MediaType!
}

"""A user’s post/publication."""
type Post {
  id:            String!
  author:        User!
  title:         String!
  description:   String!
  content:       String!
  cid:           String!
  media:         [MediaAttachment!]
  visibility:    VisibilitySetting!
  replyTo:       Post
  quoteOf:       Post
  createdAt:     Timestamp!
  updatedAt:     Timestamp

  #–– raw counts ––
  commentCount:  Int!
  likeCount:     Int!
  bookmarkCount: Int!
  viewCount:     Int!
}

input CreatePostInput {
  authorAddress:    String!
  content:    String
  title:         String!
  description:   String!
  cid:           String!
  media:      [MediaAttachmentInput!]
  visibility: VisibilitySetting!
  replyTo:    String
  quoteOf:    String
}

input UpdatePostInput {
  postId:     String!
  content:    String
  title:         String
  description:   String
  cid:           String
  visibility: VisibilitySetting
}

input MediaAttachmentInput {
  url:  String
  cid:  String
  title:  String
  type: MediaType!
}

extend type Query {
  getPost(id: String!): Post
  getPostsByAuthor(author: String!, limit: Int): [Post!]!
}

extend type Mutation {
  createPost(input: CreatePostInput!): Post!
  updatePost(input: UpdatePostInput!): Post!
  deletePost(postId: String!): Boolean!
  incrementPostView(postId: String!): Post!
}
