###########################
#        POSTS            #
###########################

####################
#     ENUMS        #
####################

enum VisibilitySetting {
  PUBLIC
  FOLLOWERS_ONLY
  PRIVATE
}

####################
#     TYPES        #
####################

type MediaAttachment {
  id: Int!
  url: String
  cid: String!
  title: String
  type: String!
}

type Post {
  id: Int!
  user: User
  title: String!
  body: String!
  createdAt: Date!
  visibility: VisibilitySetting!
  active: Boolean!
}

####################
#     INPUTS       #
####################

input HidePostInput {
  postId: String! @constraint(minLength: 1)
}

input CreatePostInput {
  title: String! @constraint(minLength: 1, maxLength: 100)
  body: String! @constraint(minLength: 10)
  visibility: VisibilitySetting!
}

input UpdatePostInput {
  postId: String! @constraint(minLength: 1)
  title: String @constraint(minLength: 1, maxLength: 100)
  body: String @constraint(minLength: 10)
  visibility: VisibilitySetting
}

input PostByIdentifierInput {
  id: Int
}

input PostFilterInput {
  id: Int
  userId: Int
}

####################
#      QUERIES     #
####################

extend type Query {
  getPost(input: PostByIdentifierInput!): Post
  getPosts(input: PostFilterInput!, pagination: PaginationInput): [Post!]!
  # getPostsByAuthor(
  #   author: String! @constraint(minLength: 1)
  #   limit: Int @constraint(min: 1, max: 100)
  # ): [Post!]!
}

####################
#     MUTATIONS    #
####################

extend type Mutation {
  createPost(input: CreatePostInput!): Post!
  updatePost(input: UpdatePostInput!): Post!
  hidePost(input: HidePostInput!): Boolean
  # incrementPostView(postId: String! @constraint(minLength: 1)): Post!
}
