###########################
#        POSTS            #
###########################

####################
#     ENUMS        #
####################

enum VisibilitySetting {
  PUBLIC
  FOLLOWERS_ONLY
  PRIVATE
}

####################
#     TYPES        #
####################

type MediaAttachment {
  id: String!
  url: String
  cid: String!
  title: String
  type: String!
}

type Post {
  id: String!
  author: User!
  title: String!
  description: String!
  cid: String!
  media: [MediaAttachment!]!
  visibility: VisibilitySetting!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  hidden: Boolean!

  #–– raw counts ––
  commentCount: Int!
  likeCount: Int!
  bookmarkCount: Int!
  viewCount: Int!
}

####################
#     INPUTS       #
####################

input MediaAttachmentInput {
  url: String @constraint(format: "uri")
  cid: String! @constraint(minLength: 1)
  title: String @constraint(maxLength: 100)
  type: String! @constraint(minLength: 1)
}

input CreatePostInput {
  title: String! @constraint(minLength: 1, maxLength: 100)
  description: String! @constraint(minLength: 10)
  cid: String! @constraint(minLength: 1)
  media: [MediaAttachmentInput!]!
  visibility: VisibilitySetting!
}

input UpdatePostInput {
  postId: String! @constraint(minLength: 1)
  title: String @constraint(minLength: 1, maxLength: 100)
  description: String @constraint(minLength: 10)
  cid: String @constraint(minLength: 1)
  visibility: VisibilitySetting
  media: [MediaAttachmentInput!]
}

####################
#      QUERIES     #
####################

extend type Query {
  getPost(id: String! @constraint(minLength: 1)): Post
  getPosts(query: String!, limit: Int @constraint(min: 1, max: 100)): [Post!]!
  getPostsByAuthor(
    author: String! @constraint(minLength: 1)
    limit: Int @constraint(min: 1, max: 100)
  ): [Post!]!
}

####################
#     MUTATIONS    #
####################

extend type Mutation {
  createPost(input: CreatePostInput!): Post!
  updatePost(input: UpdatePostInput!): Post!
  hidePost(postId: String! @constraint(minLength: 1)): Boolean
  incrementPostView(postId: String! @constraint(minLength: 1)): Post!
}
