###########################
#    SOCIAL ACTIONS       #
###########################

"""Follow / unfollow someone."""
input FollowInput {
  targetAddress: String!
}

"""Like / unlike a post."""
input LikePostInput {
  postId: String!
}

"""Bookmark / unbookmark a post."""
input BookmarkPostInput {
  postId: String!
}

"""Like / unlike a comment."""
input LikeCommentInput {
  commentId: String!
}

extend type Mutation {
  followUser(input: FollowInput!):  Boolean!
  unfollowUser(input: FollowInput!): Boolean!

  likePost(input: LikePostInput!): Boolean!
  unlikePost(input: LikePostInput!): Boolean!

  bookmarkPost(input: BookmarkPostInput!): Boolean!
  unbookmarkPost(input: BookmarkPostInput!): Boolean!

  likeComment(input: LikeCommentInput!): Boolean!
  unlikeComment(input: LikeCommentInput!): Boolean!
}

extend type Query {
  getIsFollowing(followerAddress: String!targetAddress:   String!): Boolean!
}
