###########################
#    SOCIAL ACTIONS       #
###########################

input FollowInput        { targetAddress: String! @constraint(minLength: 1) }
input LikePostInput      { postId: String!     @constraint(minLength: 1) }
input BookmarkPostInput  { postId: String!     @constraint(minLength: 1) }
input LikeCommentInput   { commentId: String!  @constraint(minLength: 1) }

extend type Mutation {
  toggleFollow      (input: FollowInput!):        Boolean!
  togglePostLike    (input: LikePostInput!):      Boolean!
  toggleBookmark    (input: BookmarkPostInput!):  Boolean!
  toggleCommentLike (input: LikeCommentInput!):   Boolean!
}

extend type Query {
  getIsFollowing(followerAddress: String!, targetAddress: String!): Boolean!
}
