###########################
#          LOGS          #
###########################

type EventLog {
  id:          String!
  type:        String!
  author:      String
  targetId:    String
  targetType:  String
  progress:    Int
  amount:      Int
  currency:    String
  meta:        JSON
  createdAt:   Timestamp!
}

input LogEventInput {
  type:        String!     @constraint(minLength: 1)
  targetId:    String
  targetType:  String
  progress:    Int
  amount:      Int
  currency:    String
  meta:        JSON
}

###########################
#       MUTATIONS         #
###########################
extend type Mutation {
  logEvent(input: LogEventInput!): Boolean!
  logAnonymousEvent(input: LogEventInput!): Boolean!
}

###########################
#        QUERIES          #
###########################
extend type Query {
  getUserEvents(
    address: String! @constraint(minLength: 1)
    type:    String
    limit:   Int = 50  @constraint(min: 1, max: 200)
    offset:  Int = 0   @constraint(min: 0)
  ): [EventLog!]!

  getTargetEvents(
    targetId:   String! @constraint(minLength: 1)
    targetType: String
    type:       String
    limit:      Int = 50
    offset:     Int = 0
  ): [EventLog!]!

  getPostViews(postId: String!): Int!
  getProfileViews(address: String!): Int!
}
