###########################
#      USERS SCHEMA       #
###########################

####################
#      TYPES       #
####################

type SocialLink {
  platform: String
  url: String
}

type User {
  address: String!
  username: String
  displayName: String
  bio: String
  profilePicture: String
  coverPicture: String
  socialLinks: [SocialLink]

  followersCount: Int!
  followingCount: Int!
  publicationsCount: Int!
  bookmarksCount:    Int!

  verified: Boolean
  createdAt: Timestamp!
  updatedAt: Timestamp!
}


####################
#     INPUTS       #
####################

input UserInput {
  address: String!
  username: String
  displayName: String
  bio: String
  profilePicture: String
  coverPicture: String

  socialLinks: [SocialLinkInput!]
}

input UserByInput {
  address: String
}

input UpdateUserInput {
  address: String!
  username: String
  displayName: String
  bio: String
  profilePicture: String
  coverPicture: String
  socialLinks: [SocialLinkInput!]
}

input SocialLinkInput {
  platform: String
  url: String
}

####################
#      QUERIES     #
####################

extend type Query {
  getUser(address: String!): User
  getUsers(prefix: String!, limit: Int): [User!]!
  getUserFollowers(address: String!, limit: Int): [User!]!
  getUserFollowing(address: String!, limit: Int): [User!]!
  getUserBookmarks(address: String!, limit: Int): [Post!]!
}

####################
#     MUTATIONS    #
####################

extend type Mutation {
  createUser(input: UserInput!): User!
  updateUser(input: UpdateUserInput!): User!
}
