###########################
#       COMMENTS          #
###########################

"""
A comment on a post, or a reply to another comment.
"""
type Comment {
  id: String!
  author: User!
  content: String!
  post: Post!
  parentComment: Comment
  createdAt: Timestamp!
  updatedAt: Timestamp!
  hidden: Boolean!

  #–– raw count ––
  likeCount: Int!
  repliesCount: Int!
}

####################
#     INPUTS       #
####################

input CreateCommentInput {
  postId: String! @constraint(minLength: 1)
  parentComment: String @constraint(minLength: 1)
  content: String! @constraint(minLength: 1, maxLength: 500)
}

input UpdateCommentInput {
  commentId: String! @constraint(minLength: 1)
  content: String! @constraint(minLength: 1, maxLength: 500)
}

####################
#      QUERIES     #
####################

extend type Query {
  getCommentsByPost(
    postId: String! @constraint(minLength: 1)
    limit: Int @constraint(min: 1, max: 100)
  ): [Comment!]!

  getRepliesByComment(
    commentId: String! @constraint(minLength: 1)
    limit: Int @constraint(min: 1, max: 100)
  ): [Comment!]!
}

####################
#     MUTATIONS    #
####################

extend type Mutation {
  createComment(input: CreateCommentInput!): Comment!
  updateComment(input: UpdateCommentInput!): Comment!
  hideComment(commentId: String! @constraint(minLength: 1)): Boolean
}
