###########################
#       COMMENTS          #
###########################

"""A comment on a post, or a reply to another comment."""
type Comment {
  id:             String!
  author:         User!
  post:           Post!
  parentComment:  Comment
  createdAt:      Timestamp!
  updatedAt:      Timestamp

  #–– raw count ––
  likeCount:      Int!

  content:        String!
}

input CreateCommentInput {
  authorAddress: String!
  postId:        String!
  parentComment: String
  content:       String!
}

input UpdateCommentInput {
  commentId: String!
  content:   String!
}

extend type Query {
  getCommentsByPost(postId: String!, limit: Int):    [Comment!]!
  getRepliesByComment(commentId: String!, limit: Int): [Comment!]!
}

extend type Mutation {
  createComment(input: CreateCommentInput!): Comment!
  updateComment(input: UpdateCommentInput!): Comment!
  deleteComment(commentId: String!): Boolean!
}
