###########################
#       COMMENTS          #
###########################

type Comment {
  id: String!
  body: String!
  post: Post!
  parent: Comment
  replies: [Comment!]
  base: BaseContent!
}

####################
#     INPUTS       #
####################

input CreateCommentInput {
  postId: Int! @constraint(min: 1)
  parentId: Int @constraint(min: 1)
  body: String! @constraint(minLength: 1, maxLength: 500)
}

input UpdateCommentInput {
  id: Int! @constraint(min: 1)
  body: String! @constraint(minLength: 1, maxLength: 500)
}

input CommentByIdentifierInput @oneOf {
  id: Int
}

input CommentsFilterInput {
  userId: Int
  postId: Int
  parentId: Int
}

####################
#      QUERIES     #
####################

extend type Query {
  getComment(input: CommentByIdentifierInput!): Comment
  getComments(input: CommentsFilterInput!, pagination: PaginationInput): [Comment!]
}

####################
#     MUTATIONS    #
####################

extend type Mutation {
  createComment(input: CreateCommentInput!): Comment!
  updateComment(input: UpdateCommentInput!): Comment!
  # hideComment(commentId: String! @constraint(minLength: 1)): Boolean
}
