###########################
#          PERKS          #
###########################

enum PerkCategory { GAMIFICATION ECONOMY SOCIAL ACCESS }

type UnlockRule {
  on:      String!
  rankId:  String
  action:  String
  times:   Int
  window:  String
}

type ExecutionRule {
  type:        String!
  cooldownSec: Int!
}

type Reward {
  action: String!
  amount: Int
  tokenId: String
}

type Perk {
  id: String!
  name: String!
  minRankId: String!
  uiHint: String
  category: PerkCategory!
  collectedAt: Timestamp
  availableAt: Timestamp
  cooldownRemaining: Int!
  rewardPreview: String!
  unlockRule:   UnlockRule!
  executionRule:ExecutionRule!
  reward:       Reward!
  enabled:      Boolean!
}

input UnlockRuleInput {
  on:String!,
  rankId:String,
  action:String,
  times:Int,
  window:String
}

input ExecutionRuleInput {
  type:String!,
  cooldownSec:Int!
}

input RewardInput {
  action:String!,
  amount:Int,
  tokenId:String
}

input PerkInput {
  id:           String!
  name:         String!
  minRankId:    String!
  uiHint:       String
  category:     PerkCategory!
  unlockRule:   UnlockRuleInput!
  executionRule:ExecutionRuleInput!
  reward:       RewardInput!
  enabled:      Boolean!
}

extend type Query {
  getPerks: [Perk!]!
  getUnlockedPerks(address:String!, limit:Int = 50, offset:Int = 0): [Perk!]!
}

extend type Mutation {
  claimPerk(perkId:ID!): Boolean!
  createPerk(input:PerkInput!): Perk!
  updatePerk(id:ID!, patch:PerkInput!): Perk!
  deletePerk(id:ID!): Boolean!
}
