#----------------------------------------------------------------
#  root/base schema — no manual @constraint here, plugin will add it
#----------------------------------------------------------------

type Query
type Mutation
type Subscription

enum CacheControlScope {
  PUBLIC
  PRIVATE
}

directive @cacheControl(
  maxAge: Int
  scope: CacheControlScope
  inheritMaxAge: Boolean
) on FIELD_DEFINITION | OBJECT | INTERFACE | UNION

"""
ISO-8601 Date-Time string (e.g. 2024-04-17T15:22:00.000Z)
"""
scalar DateTime

"""
Unix epoch in milliseconds (number).
"""
scalar Timestamp

scalar Date
scalar JSON
scalar Upload
scalar ID

input FilterInput {
  limit: Int
  offset: Int
}
