directive @cacheControl(
  inheritMaxAge: Boolean
  maxAge: Int
  scope: CacheControlScope
) on FIELD_DEFINITION | INTERFACE | OBJECT | UNION

input AgentInput {
  message: String!
}

type AgentOutput {
  done: Boolean
  message: Message
}

type BaseContent {
  active: Boolean!
  createdAt: Date!
  id: Int!
  user: User!
  visibility: VisibilitySetting!
}

enum CacheControlScope {
  PRIVATE
  PUBLIC
}

type Comment {
  base: BaseContent!
  body: String!
  id: String!
  parent: Comment
  post: Post!
  replies(page: PaginationInput): [Comment!]
}

input CommentByIdentifierInput @oneOf {
  id: Int
}

input CommentsFilterInput {
  parentId: Int
  postId: Int
  userId: Int
}

input CreateCommentInput {
  body: String!
  parentId: Int
  postId: Int!
}

input CreatePostInput {
  body: String!
  title: String!
  visibility: VisibilitySetting!
}

input CreateTipInput {
  amount: Float!
  creator: String!
  message: String
  postId: String!
  txHash: String
}

input CreateUserInput {
  address: String!
  bio: String!
  cover: String
  displayName: String!
  picture: String
  socialLinks: [SocialLinkInput!]
  username: String!
}

scalar Date

"""
ISO-8601 Date-Time string (e.g. 2024-04-17T15:22:00.000Z)
"""
scalar DateTime

type EventLog {
  amount: Int
  author: String
  createdAt: Timestamp!
  currency: String
  id: String!
  meta: JSON
  progress: Int
  targetId: String
  targetType: String
  type: String!
}

input HidePostInput {
  postId: Int!
}

scalar JSON

input LikeInput {
  targetId: String!
  targetType: TargetType!
}

input LogEventInput {
  amount: Int
  currency: String
  meta: JSON
  progress: Int
  targetId: String
  targetType: String
  type: String!
}

type MediaAttachment {
  cid: String!
  id: Int!
  title: String
  type: String!
  url: String
}

type Message {
  content: String!
}

type Mutation {
  createComment(input: CreateCommentInput!): Comment!
  createPost(input: CreatePostInput!): Post!
  createTip(input: CreateTipInput!): Tip!
  createUser(input: CreateUserInput!): User!
  hidePost(input: HidePostInput!): Boolean
  humanMessage(input: AgentInput!): Message
  logAnonymousEvent(input: LogEventInput!): Boolean!
  logEvent(input: LogEventInput!): Boolean!
  setRelationStatus(input: SetRelationStatusInput!): Relation!
  toggleLike(input: LikeInput!): Boolean!
  updateComment(input: UpdateCommentInput!): Comment!
  updatePost(input: UpdatePostInput!): Post!
  updateUser(input: UpdateUserInput!): User!
}

input PaginationInput {
  limit: Int
  offset: Int
}

type Post {
  base: BaseContent!
  body: String!
  comments(page: PaginationInput): [Comment!]
  id: Int!
  title: String!
}

input PostByIdentifierInput @oneOf {
  id: Int
}

input PostFilterInput {
  userId: Int
}

type Profile {
  bio: String!
  cover: String
  picture: String
  username: String!
}

type Query {
  getComment(input: CommentByIdentifierInput!): Comment
  getComments(input: CommentsFilterInput!, page: PaginationInput): [Comment!]
  getCreatorTips(address: String!, limit: Int): [Tip!]!
  getIsLiked(targetId: String!): Boolean!
  getPost(input: PostByIdentifierInput!): Post
  getPostViews(postId: String!): Int!
  getPosts(input: PostFilterInput!, page: PaginationInput): [Post!]!
  getProfileViews(address: String!): Int!
  getRelationStatus(input: RelationByIdentifierInput!): Relation
  getTargetEvents(
    limit: Int = 50
    offset: Int = 0
    targetId: String!
    targetType: String
    type: String
  ): [EventLog!]!
  getTipsByBakerForPost(limit: Int, postId: String!): [TipByBaker!]!
  getTipsForPost(limit: Int, postId: String!): [Tip!]!
  getUser(input: UserByIdentifierInput!): User
  getUserEvents(address: String!, limit: Int = 50, offset: Int = 0, type: String): [EventLog!]!
  getUserTipsHistory(address: String!, limit: Int): [Tip!]!
}

type Relation {
  followedAt: Date
  isBlocked: Boolean!
  isFollowing: Boolean!
  user: User!
}

input RelationByIdentifierInput {
  toUserId: Int!
}

enum RelationState {
  BLOCK
  FOLLOW
  NONE
}

input SetRelationStatusInput {
  status: RelationState!
  toUserId: Int!
}

type SocialLink {
  platform: String!
  url: String!
}

input SocialLinkInput {
  platform: String!
  url: String!
}

input SocialsFilterInput {
  platform: String!
  userId: Int
}

type Subscription {
  onAiMessage: AgentOutput
}

enum TargetType {
  COMMENT
  POST
}

"""
Unix epoch in milliseconds (number).
"""
scalar Timestamp

type Tip {
  amount: Float!
  baker: String!
  createdAt: Timestamp!
  creator: String!
  id: String!
  message: String
  postId: String!
  txHash: String
}

type TipByBaker {
  baker: User!
  count: Float!
  lastTipAt: Timestamp!
  totalAmount: Float!
}

input UpdateCommentInput {
  body: String!
  id: Int!
}

input UpdatePostInput {
  body: String
  id: Int!
  title: String
  visibility: VisibilitySetting
}

input UpdateUserInput {
  bio: String
  cover: String
  displayName: String
  picture: String
  socialLinks: [SocialLinkInput!]
  username: String
}

scalar Upload

type User {
  address: String!
  createdAt: Timestamp!
  displayName: String!
  email: String!
  id: Int!
  profile: Profile
  socialLinks: [SocialLink!]
  verified: Boolean!
}

input UserByIdentifierInput @oneOf {
  address: String
  email: String
  id: Int
}

input UsersFilterInput {
  name: String
  verified: Boolean
}

enum VisibilitySetting {
  FOLLOWERS_ONLY
  PRIVATE
  PUBLIC
}
